# Generated by Django 3.2.16 on 2022-10-08 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('description', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('price', models.IntegerField()),
                ('is_active', models.BooleanField()),
            ],
            options={
                'db_table': 'product',
                'ordering': ['-date_created'],
            },
        ),
    ]
