# Generated by Django 3.2.16 on 2022-10-08 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20221008_1812'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('tel1', models.CharField(max_length=10)),
                ('tel2', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('invite_code', models.CharField(max_length=50)),
                ('is_active', models.BooleanField()),
            ],
            options={
                'db_table': 'customer',
                'ordering': ['-date_created'],
            },
        ),
    ]
