# Generated by Django 3.2.16 on 2022-10-08 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='book',
        ),
        migrations.AddField(
            model_name='product',
            name='price2',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
