# Generated by Django 3.2.16 on 2022-10-09 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20221008_1824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='price1',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='price2',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
