# Generated by Django 3.2.16 on 2022-10-09 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20221010_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price1',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='product',
            name='price2',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
