# Generated by Django 3.2.16 on 2022-10-12 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_place_restaurant_waiter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ['-date_created']},
        ),
        migrations.AlterModelOptions(
            name='restaurant',
            options={'ordering': ['-date_created']},
        ),
        migrations.AlterModelOptions(
            name='waiter',
            options={'ordering': ['-date_created']},
        ),
        migrations.AlterModelTable(
            name='place',
            table='place',
        ),
        migrations.AlterModelTable(
            name='restaurant',
            table='restaurant',
        ),
        migrations.AlterModelTable(
            name='waiter',
            table='waiter',
        ),
    ]
